## Data Cleaning
In this notebook, I will do data-cleaning from the raw data from here: https://communitynotes.x.com/guide/en/under-the-hood/download-data

In [1]:
import pandas as pd
import zipfile
import numpy as np

In [2]:
zip_path = '../data/raw/noteStatusHistory-00000.zip'
with zipfile.ZipFile(zip_path, 'r') as zip_ref:

  tsv_name = zip_ref.namelist()[0]
  with zip_ref.open(tsv_name) as tsv_file:
    df_nsh = pd.read_csv(tsv_file, sep='\t')

df_nsh.head()

/var/folders/jb/b4wvvt9948bgtf9ccsyfxvlc0000gn/T/ipykernel_13404/2215358326.py:6: DtypeWarning: Columns (10,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df_nsh = pd.read_csv(tsv_file, sep='\t')

,noteId,noteAuthorParticipantId,createdAtMillis,timestampMillisOfFirstNonNMRStatus,firstNonNMRStatus,timestampMillisOfCurrentStatus,currentStatus,timestampMillisOfLatestNonNMRStatus,mostRecentNonNMRStatus,timestampMillisOfStatusLock,...,currentExpansionStatus,currentGroupStatus,currentDecidedBy,currentModelingGroup,timestampMillisOfMostRecentStatusChange,timestampMillisOfNmrDueToMinStableCrhTime,currentMultiGroupStatus,currentModelingMultiGroup,timestampMinuteOfFinalScoringOutput,timestampMillisOfFirstNmrDueToMinStableCrhTime
0,1352796878438424576,B021517F4F8F9F372DCD70BB8F8A21A80C12D7EFDE8B2F...,1611366884227,NaN,NaN,1721920068424,NEEDS_MORE_RATINGS,NaN,NaN,1.674003e+12,...,NEEDS_MORE_RATINGS,NEEDS_MORE_RATINGS,CoreModel (v1.1),13.0,-1,NaN,NaN,NaN,29062194,NaN
1,1353415873227177985,D4C9EDB464DF2D4A6D8F68CA8D1F86226B50EB9D3B0F33...,1611514464087,NaN,NaN,1721920068424,NEEDS_MORE_RATINGS,NaN,NaN,1.674003e+12,...,NEEDS_MORE_RATINGS,NEEDS_MORE_RATINGS,CoreModel (v1.1),13.0,-1,NaN,NaN,NaN,29062194,NaN
2,1354586938863443971,C0AF45F4C4B2240E7AB31456957E5D770FF7AFA13627C7...,1611793667892,NaN,NaN,1721920068424,NEEDS_MORE_RATINGS,NaN,NaN,1.674003e+12,...,NEEDS_MORE_RATINGS,NEEDS_MORE_RATINGS,CoreModel (v1.1),6.0,-1,NaN,NaN,NaN,29062194,NaN
3,1354588003075764229,9C480F7B2E882F19F9FBF75BD13FEA53031875AC42FDF6...,1611793921619,NaN,NaN,1721920068424,NEEDS_MORE_RATINGS,NaN,NaN,1.674003e+12,...,NaN,NaN,ExpansionPlusModel (v1.1),NaN,-1,NaN,NaN,NaN,29062194,NaN
4,1354588172659920899,931B6CFE7C2FDF3653B0A63DC20DF3C51F8AA3BEB9D613...,1611793962051,NaN,NaN,1721920068424,NEEDS_MORE_RATINGS,NaN,NaN,1.674003e+12,...,NaN,NaN,ExpansionPlusModel (v1.1),NaN,-1,NaN,NaN,NaN,29062194,NaN

In [3]:
zip_path = '../data/raw/notes-00000.zip'
with zipfile.ZipFile(zip_path, 'r') as zip_ref:

  tsv_name = zip_ref.namelist()[0]
  with zip_ref.open(tsv_name) as tsv_file:
    df_nd = pd.read_csv(tsv_file, sep='\t')

df_nd.head()

/var/folders/jb/b4wvvt9948bgtf9ccsyfxvlc0000gn/T/ipykernel_13404/2096223128.py:6: DtypeWarning: Columns (5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_nd = pd.read_csv(tsv_file, sep='\t')

,noteId,noteAuthorParticipantId,createdAtMillis,tweetId,classification,believable,harmful,validationDifficulty,misleadingOther,misleadingFactualError,...,misleadingUnverifiedClaimAsFact,misleadingSatire,notMisleadingOther,notMisleadingFactuallyCorrect,notMisleadingOutdatedButNotWhenWritten,notMisleadingClearlySatire,notMisleadingPersonalOpinion,trustworthySources,summary,isMediaNote
0,1783179305159200982,C784F04F26E124F4D6EC01658D8F5565005D3092741FB3...,1713978050878,1783159712986382830,MISINFORMED_OR_POTENTIALLY_MISLEADING,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,1,The House failed to pass a border protection l...,0
1,1783181538789605871,C784F04F26E124F4D6EC01658D8F5565005D3092741FB3...,1713978583415,1783171851818021181,MISINFORMED_OR_POTENTIALLY_MISLEADING,NaN,NaN,NaN,0,1,...,1,0,0,0,0,0,0,1,The United States has 50 States https://da...,0
2,1783182562279494134,C784F04F26E124F4D6EC01658D8F5565005D3092741FB3...,1713978827435,1783154445682979015,MISINFORMED_OR_POTENTIALLY_MISLEADING,NaN,NaN,NaN,0,0,...,0,0,0,0,0,0,0,1,TikTok only mentions “ban” and chooses to igno...,0
3,1883711635770196070,C784F04F26E124F4D6EC01658D8F5565005D3092741FB3...,1737946826294,1883619411774345444,MISINFORMED_OR_POTENTIALLY_MISLEADING,NaN,NaN,NaN,1,0,...,0,0,0,0,0,0,0,1,This could be considered a threat https://...,0
4,1537142913737428992,5684B38EB58FD8BE75ABA37F0BE040EC70380B002ADF9D...,1655318404027,1377030478167937024,MISINFORMED_OR_POTENTIALLY_MISLEADING,BELIEVABLE_BY_MANY,CONSIDERABLE_HARM,EASY,0,1,...,1,0,0,0,0,0,0,1,Forbes has a good rundown of the investigation...,0

### Merge two dataframes on "note ID"

In [4]:
df_merged = pd.merge(df_nsh, df_nd, on=['noteId','createdAtMillis'])

df_merged = df_merged[["summary", "currentStatus", "createdAtMillis"]]
df_merged.head()

,summary,currentStatus,createdAtMillis
0,Wikipedia entry for whales https://en.m.wik...,NEEDS_MORE_RATINGS,1611793667892
1,example,NEEDS_MORE_RATINGS,1611793921619
2,This tweet is just explaining how to do someth...,NEEDS_MORE_RATINGS,1611793962051
3,This is a test,NEEDS_MORE_RATINGS,1611794172392
4,Dispassionate explanatory tweet with optimisti...,NEEDS_MORE_RATINGS,1611794328036

In [5]:
df = df_merged

### Clean the data to meet the following conditions
- "currentStatus" is either "CURRENTLY_RATED_HELPFUL" or "CURRENTLY_RATED_NOT_HELPFUL"
- Notes posted from 2024-01-01 to 2024-12-31
- "summary" includes "Trump" or "Biden" or "Kamala" or "Harris
- Notes in English

In [6]:
df['currentStatus'] = df["currentStatus"].replace('NEEDS_MORE_RATINGS', np.nan)
df = df.dropna(subset = "currentStatus")

df.head()

,summary,currentStatus,createdAtMillis
12,Despite raising money for charity the women’s ...,CURRENTLY_RATED_NOT_HELPFUL,1611796813041
22,The stocks subreddit WallStreetBets was not sh...,CURRENTLY_RATED_HELPFUL,1611850121474
23,The headline in this photo does not appear on ...,CURRENTLY_RATED_HELPFUL,1611850916145
43,"The stock market is deregulated, and it in fac...",CURRENTLY_RATED_HELPFUL,1611852016783
77,Robinhood barred users from buying but continu...,CURRENTLY_RATED_HELPFUL,1611852802333

In [7]:
import datetime

# change unix into datetime
df["datetime"] = df["createdAtMillis"]
for i in range(len(df)):
    df["datetime"].iloc[i] = datetime.datetime.fromtimestamp(df["createdAtMillis"].iloc[i] / 1000)
    df["datetime"].iloc[i] = df["datetime"].iloc[i].strftime("%Y-%m-%d")
    
df = df[(df["datetime"] >= "2024-01-01") & (df["datetime"] <= "2024-12-31")]
df.head()

/var/folders/jb/b4wvvt9948bgtf9ccsyfxvlc0000gn/T/ipykernel_13404/1185128922.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["datetime"] = df["createdAtMillis"]
/var/folders/jb/b4wvvt9948bgtf9ccsyfxvlc0000gn/T/ipykernel_13404/1185128922.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["datetime"].iloc[i] = datetime.datetime.fromtimestamp(df["createdAtMillis"].iloc[i] / 1000)
/var/folders/jb/b4wvvt9948bgtf9ccsyfxvlc0000gn/T/ipykernel_13404/1185128922.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["datetime"].iloc[i] = datetime.datetime.fromtimestamp(df["createdAtMillis"].iloc[i] / 1000)
/var/folders/jb/b4wvvt9948bgtf9ccsyfxvlc0000gn/T/ipykernel_13404/1185128922.py:6: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '2021-01-28 10:20:13.041000' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df["datetime"].iloc[i] = datetime.datetime.fromtimestamp(df["createdAtMillis"].iloc[i] / 1000)
/var/folders/jb/b4wvvt9948bgtf9ccsyfxvlc0000gn/T/ipykernel_13404/1185128922.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["datetime"].iloc[i] = df["datetime"].iloc[i].strftime("%Y-%m-%d")
/var/folders/jb/b4wvvt9948bgtf9ccsyfxvlc0000gn/T/ipykernel_13404/1185128922.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["datetime"].iloc[i] = df["datetime"].iloc[i].strftime("%Y-%m-%d")
/var/folders/jb/b4wvvt9948bgtf9ccsyfxvlc0000gn/T/ipykernel_13404/1185128922.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["datetime"].iloc[i] = datetime.datetime.fromtimestamp(df["createdAtMillis"].iloc[i] / 1000)

,summary,currentStatus,createdAtMillis,datetime
417124,"De acordo com o noticiário local, o senhor Ant...",CURRENTLY_RATED_HELPFUL,1704034943578,2024-01-01
417127,This is a scam. Domain is 18 days old - https...,CURRENTLY_RATED_HELPFUL,1704035094666,2024-01-01
417133,This is a scam to steal your information and d...,CURRENTLY_RATED_HELPFUL,1704035201616,2024-01-01
417134,Antony has score 4 goals in 2023. https://w...,CURRENTLY_RATED_HELPFUL,1704035205215,2024-01-01
417137,The like animation for #Haaland does not exist...,CURRENTLY_RATED_HELPFUL,1704035435339,2024-01-01

In [8]:
df = df[df["summary"].str.contains(r"Kamala|Harris|Donald Trump|Trump|Joe Biden|Biden", case=False, na=False)]
df.head(5)

,summary,currentStatus,createdAtMillis,datetime
417810,Trump posted on Truth Social on 12/30/2023 tha...,CURRENTLY_RATED_HELPFUL,1704054854654,2024-01-01
418566,This has been refuted multiple times as false....,CURRENTLY_RATED_HELPFUL,1704090450017,2024-01-01
419789,Trump hat das nie gesagt. https://correctiv...,CURRENTLY_RATED_HELPFUL,1704120478961,2024-01-01
420069,"This story was updated, originally reporting t...",CURRENTLY_RATED_HELPFUL,1704126932804,2024-01-02
420682,This is not true. Joe Biden led the 2020 Democ...,CURRENTLY_RATED_HELPFUL,1704143134287,2024-01-02

In [9]:
import langid

df = df[df["summary"].apply(lambda x: langid.classify(x)[0] == "en")]

In [10]:
# download the file
df.to_csv('../data/processed/notes_2024.csv', index=False)

### Extract FQDN

In [11]:
import re

def extract_fqdn_list(text):
    if pd.isna(text):
        return []
    pattern = r"https://([a-zA-Z0-9.-]+)"
    domains = re.findall(pattern, str(text))
    return domains

df['fqdn'] = df['summary'].apply(extract_fqdn_list)

df.head()

,summary,currentStatus,createdAtMillis,datetime,fqdn
417810,Trump posted on Truth Social on 12/30/2023 tha...,CURRENTLY_RATED_HELPFUL,1704054854654,2024-01-01,"[www.newsweek.com, pbs.twimg.com, truthsocial...."
418566,This has been refuted multiple times as false....,CURRENTLY_RATED_HELPFUL,1704090450017,2024-01-01,"[www.factcheck.org, www.reuters.com, apnews.com]"
420069,"This story was updated, originally reporting t...",CURRENTLY_RATED_HELPFUL,1704126932804,2024-01-02,"[www.politifact.com, www.npr.org]"
420682,This is not true. Joe Biden led the 2020 Democ...,CURRENTLY_RATED_HELPFUL,1704143134287,2024-01-02,"[www.realclearpolitics.com, www.politico.com]"
421081,Author has posted a selectively edited photo o...,CURRENTLY_RATED_HELPFUL,1704154725026,2024-01-02,[t.co]

In [12]:
df = df.reset_index()
df = df.drop(columns=['index'])
df.head()

,summary,currentStatus,createdAtMillis,datetime,fqdn
0,Trump posted on Truth Social on 12/30/2023 tha...,CURRENTLY_RATED_HELPFUL,1704054854654,2024-01-01,"[www.newsweek.com, pbs.twimg.com, truthsocial...."
1,This has been refuted multiple times as false....,CURRENTLY_RATED_HELPFUL,1704090450017,2024-01-01,"[www.factcheck.org, www.reuters.com, apnews.com]"
2,"This story was updated, originally reporting t...",CURRENTLY_RATED_HELPFUL,1704126932804,2024-01-02,"[www.politifact.com, www.npr.org]"
3,This is not true. Joe Biden led the 2020 Democ...,CURRENTLY_RATED_HELPFUL,1704143134287,2024-01-02,"[www.realclearpolitics.com, www.politico.com]"
4,Author has posted a selectively edited photo o...,CURRENTLY_RATED_HELPFUL,1704154725026,2024-01-02,[t.co]

In [13]:
## make a media list
media_classifier = {
    ## twitter
    "twitter.com" : "x.com",
    'help.x.com' : "x.com",
    'help.twitter.com' : "x.com",
    't.co' : "x.com",
    ## Reuters
    'fingfx.thomsonreuters.com' : "www.reuters.com	", 
    'pictures.reuters.com' : "www.reuters.com",
    'jp.reuters.com' : "www.reuters.com",
    ## apnews
    'newsroom.ap.org' : 'apnews.com',
    ## wikipedia
    'en.wikipedia.org' : 'en.m.wikipedia.org',
    ## youtube
    'youtu.be' : "www.youtube.com",
    ## newsweek
    'd.newsweek.com' : 'www.newsweek.com',
    #nyt
    'archive.nytimes.com': "www.nytimes.com",
    'static01.nytimes.com' : "www.nytimes.com",
    #cnn
    'edition.cnn.com': 'www.cnn.com',
    'amp.cnn.com': 'www.cnn.com',
    'transcripts.cnn.com': 'www.cnn.com',
    'media.cnn.com': 'www.cnn.com',
    'cnn.com': 'www.cnn.com',
    # usatoday
    'eu.usatoday.com' : 'www.usatoday.com',
    # truthsocial
    'trumpstruth.org' : 'truthsocial.com',
    # cbs
    'cbsaustin.com' : 'www.cbsnews.com',
    # archive groups (TO BE CONSIDERED LATER)
    'web.archive.org' : "archive.ph" ,
    'archive.org':"archive.ph",
    'archive.fo':"archive.ph",
    'archive.is':"archive.ph",
    # npr
    'npr.org' : 'www.npr.org',
    'apps.npr.org' :'www.npr.org',
    # fox
    'www.foxbusiness.com': 'www.foxnews.com',
    'www.fox26houston.com': 'www.foxnews.com',
    'www.livenowfox.com': 'www.foxnews.com',
    'www.fox6now.com': 'www.foxnews.com',
    'www.foxla.com': 'www.foxnews.com',
    'okcfox.com': 'www.foxnews.com',
    'www.fox28spokane.com': 'www.foxnews.com',
    'www.fox4news.com': 'www.foxnews.com',
    'www.fox43.com': 'www.foxnews.com',
    'www.fox13seattle.com': 'www.foxnews.com',
    'www-foxbusiness-com.cdn.ampproject.org': 'www.foxnews.com',
    'www.foxcarolina.com': 'www.foxnews.com',
    'www.fox13news.com': 'www.foxnews.com',
    'myfox8.com': 'www.foxnews.com',
    'www.fox5ny.com': 'www.foxnews.com',
    'fox5sandiego.com': 'www.foxnews.com',
    'a57.foxnews.com': 'www.foxnews.com',
    'static.foxnews.com': 'www.foxnews.com',
    'fox59.com': 'www.foxnews.com',
    'www.fox19.com': 'www.foxnews.com',
    # google groups (TO BE CONSIDERED LATER)
    'trends.google.com': 'www.google.com',
    #'books.google.co.uk': 'www.google.com',
    'translate.google.com': 'www.google.com',
    'www.google.ca': 'www.google.com',
    'www.google.com.au': 'www.google.com',
    # guardian
    'amp.theguardian.com': "www.theguardian.com", 
    'wwe.theguardian.com': "www.theguardian.com",
    # factcheck
    'factcheck.org' : "www.factcheck.org",
    # bbc
    'www.bbc.co.uk' : 'www.bbc.com',
    # abcnews
    'www.abc.net.au': 'abcnews.go.com',
    'abc7news.com': 'abcnews.go.com',
    'cdn.abcotvs.com': 'abcnews.go.com',
    'abc7chicago.com': 'abcnews.go.com',
    'abc7ny.com': 'abcnews.go.com',
    'www.abc10.com': 'abcnews.go.com',
    'abcnews4.com': 'abcnews.go.com',
    'abc7.com': 'abcnews.go.com',
    '6abc.com': 'abcnews.go.com',
    # forbes
    'www.forbesindia.com' : 'www.forbes.com',
    # nbc
    'www.cnbc.com': 'www.nbcnews.com',
    'www.nbcnewyork.com': 'www.nbcnews.com',
    'www.msnbc.com': 'www.nbcnews.com',
    'www.nbcchicago.com': 'www.nbcnews.com',
    'mynbc15.com': 'www.nbcnews.com',
    'www.nbc.com': 'www.nbcnews.com',
    'nbcmontana.com': 'www.nbcnews.com',
    'www.nbcbayarea.com': 'www.nbcnews.com',
    'www.nbcmiami.com': 'www.nbcnews.com',
    # independent
    'www.the-independent.com' : 'www.independent.co.uk', 
    # time
    'api.time.com' : "time.com",
    'content.time.com' : "time.com",
    # pbs
    'pbs.twimg.com' : 'www.pbs.org',
    # businessinsider
    "www.businessinsider.in" : 'www.businessinsider.com',
    # gettyimages
    'www.gettyimages.ca': 'www.gettyimages.com',
    'www.gettyimages.co.uk': 'www.gettyimages.com',
    'www.gettyimages.ae': 'www.gettyimages.com',
    'www.gettyimages.de': 'www.gettyimages.com',
    'www.gettyimages.nl': 'www.gettyimages.com',
    # facebook
    'm.facebook.com' : "www.facebook.com",
    "fb.watch" : "www.facebook.com",
    # the sun
    'www.thesun.co.uk' : 'www.the-sun.com',
    # rollingstone
    'qc.rollingstone.com' : 'www.rollingstone.com',
    # congress
    'constitution.congress.gov' : 'www.congress.gov',
    'crsreports.congress.gov': 'www.congress.gov',
    'bioguideretro.congress.gov': 'www.congress.gov',
    # aljazeera
    'www-aljazeera-com.cdn.ampproject.org' : 'www.aljazeera.com',
    # bloomberg
    "www.bnnbloomberg.ca" : 'www.bloomberg.com',
    # skynews
    'www.skynews.com.au' : "news.sky.com",
    # yahoo
    'finance.yahoo.com': 'www.yahoo.com',
    'news.yahoo.com': 'www.yahoo.com',
    'au.news.yahoo.com': 'www.yahoo.com',
    'uk.news.yahoo.com': 'www.yahoo.com',
    'uk.finance.yahoo.com': 'www.yahoo.com',
    'ca.finance.yahoo.com': 'www.yahoo.com',
    'nz.finance.yahoo.com': 'www.yahoo.com',
    'malaysia.news.yahoo.com': 'www.yahoo.com',
    'ca.news.yahoo.com': 'www.yahoo.com',
    # financial times
    'ig.ft.com':'www.ft.com'
    
}

#### Google & archive
- www.google.com does not always mean that they used "Google" as a source -> treat the true FQDN as the source
    - e.g. www.google.com/cnn.com 
- archive is a website to archive sites to retrieve the sites in case that they are deleted -> treat the true site as the source

In [14]:
#fqdn update for Google
google_updates = {
    376: ["www.aljazeera.com"],
    419: ["thehill.com", "www.forbes.com"],
    538: ["abcnews.go.com"],
    775: ["www.rollingstone.com", "twitter.com", "twitter.com", "people.com"],
    822: ["www.news18.com"],
    920: ["www.usatoday.com", "www.news.com.au", "www.nj.com"],
    936: ["www.aljazeera.com"],
    1051: ["amp.cnn.com"],
    1490: ["www.bbc.com"],
    1546: ["twitter.com"],
    1932: ["trumpwhitehouse.archives.gov", "trumpwhitehouse.archives.gov"],
    1935: ["timesofindia.indiatimes.com"],
    2329: ["www.aljazeera.com", "www.npr.org", "edition.cnn.com"],
    2365: ["m.economictimes.com"],
    2425: ["www.dailymail.co.uk"],
    2453: ["www.hollywoodreporter.com", "www.rollingstone.com"],
    2671: ["amp.tmz.com"],
    3026: ["www.cnbc.com"],
    3147: ["www.aljazeera.com", "www.dailysabah.com", "www.palestinechronicle.com"],
    3236: ["personality-politics.org"],
    3550: ["amp.theguardian.com"],
    3632: ["www.foxnews.com"],
    3646: ["www.amazon.com"],
    3996: ["www.cbsnews.com"],
    4162: ["amp.dw.com"],
    4134: ["amp.theguardian.com", "x.com"]
}

# replace the fqdn in the dataframe
for index, fqdn_list in google_updates.items():
    df.at[index, "fqdn"] = fqdn_list

In [15]:
# fqdn update for archive
archive_updates_1 = {
    960: ["apnews.com", "www.newsweek.com", "d.newsweek.com", "newsroom.ap.org", "www.factcheck.org", "blogs.abcnews.com"],
    1372: ["x.com","twitter.com", "twitter.com", "www.instagram.com"],
    1815: ["apnews.com","whyy.org", "www.usatoday.com", "www.factcheck.org", "www.reuters.com", "bustatroll.org"],
    2043: ["www.govtrack.us", "www.vox.com"],
    2110: ["twitter.com"],
    2250: ["www.facebook.com", "x.com", "www.reuters.com"],
    2707: ["www.jpain.org", "www.dea.gov", "kamalaharris.com"],
    2753: ["x.com","countylocalnews.com", "countylocalnews.com"],
    2801: ["www.lawyersclubindia.com", "utahefps.com", "www.reuters.com", "factcheck.afp.com", "www.politifact.com", "fintel.io", "nhatrangtrongtoi.site", "www.lawyersclubindia.com", "factcheck.afp.com"],
    2905: ["transcripts.cnn.com"," grabien.com", "www.cnn.com", "apnews.com", "time.com", "www.cnn.com"],
    2906: ["transcripts.cnn.com"," grabien.com", "www.cnn.com", "apnews.com", "time.com", "www.cnn.com"],
    2907: ["transcripts.cnn.com"," grabien.com", "www.cnn.com", "apnews.com", "time.com", "www.cnn.com"],
    2908: ["transcripts.cnn.com"," grabien.com", "www.cnn.com", "apnews.com", "time.com", "www.cnn.com"],
    2909: ["transcripts.cnn.com"," grabien.com", "www.cnn.com", "apnews.com", "time.com", "www.cnn.com"],
    2910: ["transcripts.cnn.com"," grabien.com", "www.cnn.com", "apnews.com", "time.com", "www.cnn.com"],
    2916: ["transcripts.cnn.com"," grabien.com", "www.cnn.com", "apnews.com", "time.com", "www.cnn.com"],
    2917: ["transcripts.cnn.com"," grabien.com", "www.cnn.com", "apnews.com", "time.com", "www.cnn.com"],
    3032: ["en.wikiquote.org","www.marxists.org", "jack488.substack.com", "trends.google.com","www.google.com", "en.wikipedia.org"],
    3275: ["projects.propublica.org","twitter.com", "www.reuters.com","apnews.com", "www.vpm.org", "www.poynter.org"," www.politifact.com", "www.snopes.com", "www.stltoday.com", "www.factcheck.org", "www.newsweek.com", "twitter.com"],
    3348: ["www.tiktok.com", "www.snopes.com"],
    3364: ["pbs.twimg.com"],
    3938: ["www.usatoday.com", "www.verifythis.com", "kamalaharris.com", "www.cbsnews.com", "www.reuters.com"],
    3986: ["notesbywalt.substack.com", "www.google.com", "www.usatoday.com", "x.com", "pluginamerica.org", "notesbywalt.substack.com","www.congress.gov", "www.fhwa.dot.gov", "archive.ph", "www.factcheck.org", "www.fhwa.dot.gov", "www.fhwa.dot.gov"],
    4029: ["www.reuters.com", "video.weibo.com", "www.dailymail.co.uk"],
    4224: ["www.snopes.com", "www.reuters.com", "apnews.com", "edition.cnn.com", "www.politifact.com", "www.news.com.au", "www.thejournal.ie", "newschecker.in"]
}

# replace
for index, fqdn_list in archive_updates_1.items():
    df.at[index, "fqdn"] = fqdn_list
    
archive_updates_2 = {
    1752: ["www.techarp.com", "factcheck.afp.com", "www.washingtonpost.com"],
    1866: ["www.techarp.com", "www.reuters.com", "www.facebook.com", "x.com"],
    1878: ["www.snopes.com"," www.reuters.com", "www.facebook.com", "www.tiktok.com", "x.com"],
    2488: ["x.com", "x.com", "x.com"],
    2546: ["x.com", "x.com", "x.com", "x.com", "x.com", "x.com"],
    2593: ["x.com", "x.com", "x.com", "x.com", "x.com", "x.com"],
    2605: ["x.com", "x.com", "x.com", "x.com", "x.com", "x.com"],
    2719: ["truthsocial.com"],
    2892: ["www.instagram.com", "instagram.fmli1-1.fna.fbcdn.net"],
    2902: ["www.forbes.com", "en.wikipedia.org", "www.espn.com", "twitter.com", "trends.google.com", "trends.google.com", "apnews.com"],
    2918: ["x.com", "x.com", "x.com", "x.com", "x.com", "x.com", "x.com", "x.com", "x.com", "x.com"],
    2948: ["www.reuters.com", "www.factcheck.org", "www.snopes.com", "www.politifact.com", "therightists.com", "therightists.com"],
    2952: ["factcheck.afp.com", "www.whitehouse.gov", "www.snopes.com", "www.politifact.com", "www.usatoday.com"],
    3051: ["x.com", "patriots.win", "en.wikipedia.org", "www.dailydot.com", "x.com"],
    3075: ["factcheck.afp.com", "www.whitehouse.gov", "www.snopes.com", "www.federalregister.gov", "www.politifact.com", "www.usatoday.com"],
    3090: ["x.com", "x.com", "x.com", "x.com", "x.com", "x.com"],
    3152: ["x.com", "www.reddit.com", "www.reddit.com"],
    3167: ["www.theatlantic.com", "www.theatlantic.com", "x.com"],
    3324: ["reganfamily.ca", "www.pinterest.com", "reganfamily.ca"],
    3325: ["reganfamily.ca", "www.pinterest.com", "reganfamily.ca"],
    3331: ["reganfamily.ca", "www.pinterest.com", "reganfamily.ca"],
    3333: ["x.com", "x.com", "x.com", "www.facebook.com"],
    3334: ["x.com", "x.com", "x.com", "www.facebook.com"],
    3335: ["x.com", "x.com", "x.com", "www.facebook.com"],
    3336: ["x.com", "www.facebook.com"],
    3349: ["x.com", "x.com", "x.com", "x.com", "x.com", "www.facebook.com"],
    3362: ["forward.com", "www.nytimes.com", "forward.com", "www.nytimes.com"],
    3415: ["x.com", "mielections.csod.com", "x.com"],
    3416: ["x.com", "mielections.csod.com", "x.com"],
    3419: ["x.com", "mielections.csod.com", "x.com"],
    3420: ["x.com", "mielections.csod.com", "x.com"],
    3424: ["x.com", "mielections.csod.com", "x.com"],
    3435: ["x.com", "www.reuters.com", "www.gettyimages.com"],
    3529: ["www.techarp.com", "x.com", "x.com", "x.com", "x.com", "x.com"],
    3582: ["www.google.com", "www.google.com", "x.com", "x.com", "www.google.com"],
    3586: ["www.google.com", "www.google.com", "x.com", "x.com", "www.googlw.com"],
    3821: ["rollcall.com", "apnews.com", "www.npr.org", "www.nytimes.com"],
    3822: ["rollcall.com", "apnews.com", "www.npr.org", "www.nytimes.com"],
    3978: ["www.washingtonpost.com", "www.washingtonpost.com"],
    3986: ["notesbywalt.substack.com", "www.google.com", "www.usatoday.com", "x.com", "pluginamerica.org", "notesbywalt.substack.com", "www.congress.gov", "www.fhwa.dot.gov", "www.factcheck.org", "www.fhwa.dot.gov", "www.fhwa.dot.gov"]

}

# replace
for index, fqdn_list in archive_updates_2.items():
    df.at[index, "fqdn"] = fqdn_list

In [16]:
def replace_domains(domain_list):
    return [media_classifier.get(domain, domain) for domain in domain_list]

df["fqdn_replaced"] = df["fqdn"].apply(replace_domains)
df.head()

,summary,currentStatus,createdAtMillis,datetime,fqdn,fqdn_replaced
0,Trump posted on Truth Social on 12/30/2023 tha...,CURRENTLY_RATED_HELPFUL,1704054854654,2024-01-01,"[www.newsweek.com, pbs.twimg.com, truthsocial....","[www.newsweek.com, www.pbs.org, truthsocial.com]"
1,This has been refuted multiple times as false....,CURRENTLY_RATED_HELPFUL,1704090450017,2024-01-01,"[www.factcheck.org, www.reuters.com, apnews.com]","[www.factcheck.org, www.reuters.com, apnews.com]"
2,"This story was updated, originally reporting t...",CURRENTLY_RATED_HELPFUL,1704126932804,2024-01-02,"[www.politifact.com, www.npr.org]","[www.politifact.com, www.npr.org]"
3,This is not true. Joe Biden led the 2020 Democ...,CURRENTLY_RATED_HELPFUL,1704143134287,2024-01-02,"[www.realclearpolitics.com, www.politico.com]","[www.realclearpolitics.com, www.politico.com]"
4,Author has posted a selectively edited photo o...,CURRENTLY_RATED_HELPFUL,1704154725026,2024-01-02,[t.co],[x.com]

In [18]:
df.to_csv('../data/processed/notes_2024_fqdn.csv', index=False)